name: Build and Deploy

on:
  push:
    branches: [ template ]

jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'no-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Install and Test
        run: |
          npm install
          npm run test

      - name: Github Fix
        run: sh utils/github.io_fix.sh

      - name: Preprocess
        run: npm run prestart

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true
          external_repository: igembitsgoa/wiki-template

      - name: Add Changes to Git
        run: git add src/citations/cache.yml

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Successfully built and deployed to Github [no-ci]" || echo "No changes to commit"

      - name: Push Changes to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: template
  
  iGEM:
    if: "!contains(github.event.head_commit.message, 'no-ci') && \
          contains(github.event.head_commit.message, 'iGEM-deploy')"
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Install and Test
        run: |
          npm install
          npm run test

      - name: Preprocess
        run: npm run prestart

      - name: Build
        run: npm run build

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: iGEM WikiSync
        uses: igembitsgoa/wikisync-action@v0.2
        with:
          team: 'BITSPilani-Goa_India'
          source: 'dist'
          build: 'igem'
        env:
          IGEM_USERNAME: ${{ secrets.IGEM_USERNAME }}
          IGEM_PASSWORD: ${{ secrets.IGEM_PASSWORD }}

      - name: Print Upload Map
        run: cat upload_map.yml

      - name: Add Changes to Git
        run: git add src/citations/cache.yml upload_map.yml wikisync.log dist igem

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Successfully built and deployed to iGEM [no-ci]" || echo "No changes to commit"

      - name: Push Changes to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}